"""Farm submitter export helpers (Deadline and Tractor).

Turns a list of :class:`RenderJob` instances into Thinkbox Deadline job files
or Pixar Tractor .alf scripts.
"""

from __future__ import annotations

import os
from typing import Sequence

from .husk import RenderJob, build_command, format_command


def export_deadline_job(jobs: Sequence[RenderJob], output_dir: str,
                        job_name: str = "Solaris Render") -> tuple[str, str]:
    """Write Thinkbox Deadline job info and plugin info files.

    Returns (job_info_path, plugin_info_path).
    """
    os.makedirs(output_dir, exist_ok=True)
    job_info_path = os.path.join(output_dir, "deadline_job.job")
    plugin_info_path = os.path.join(output_dir, "plugin_info.job")

    first_job = jobs[0] if jobs else RenderJob()
    frames = ",".join(str(j.chunk) for j in jobs)

    with open(job_info_path, "w", encoding="utf-8") as fh:
        fh.write(f"Plugin=CommandLine\n")
        fh.write(f"Name={job_name}\n")
        fh.write(f"Comment=Generated by Solaris Render Launcher\n")
        fh.write(f"Frames={frames}\n")
        fh.write(f"ChunkSize=1\n")

    with open(plugin_info_path, "w", encoding="utf-8") as fh:
        fh.write(f"Executable={first_job.husk_exe or 'husk'}\n")
        cmd_args = format_command(build_command(first_job)[1:])
        fh.write(f"Arguments={cmd_args}\n")

    return job_info_path, plugin_info_path


def export_tractor_job(jobs: Sequence[RenderJob], output_path: str,
                       job_name: str = "Solaris Render") -> str:
    """Write Pixar Tractor .alf script file.

    Returns output_path.
    """
    out_dir = os.path.dirname(os.path.abspath(output_path))
    if out_dir:
        os.makedirs(out_dir, exist_ok=True)

    lines = [
        f'#Alfred-1.0',
        f'Job -title {{{job_name}}} -subservice {{husk}} -title {{{job_name}}} -children {{',
    ]

    for i, job in enumerate(jobs, start=1):
        argv = build_command(job)
        cmd_str = " ".join(f'"{arg}"' if " " in arg else arg for arg in argv)
        lines.append(f'  Task -title {{{job.label}}} -cmds {{')
        lines.append(f'    RemoteCmd {{{cmd_str}}}')
        lines.append(f'  }}')

    lines.append('}')

    with open(output_path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")

    return output_path
