"""Farm submitter export helpers (Deadline and Tractor).

Turns a list of :class:`RenderJob` instances into Thinkbox Deadline job files
or Pixar Tractor .alf scripts.
"""

from __future__ import annotations

import os
from typing import Sequence

from .husk import RenderJob, build_command, format_command

# Deadline's CommandLine plugin substitutes these per task before running it.
DEADLINE_START_TOKEN = "<STARTFRAME>"


def all_frames(jobs: Sequence[RenderJob]) -> list[int]:
    """Every frame the jobs cover, deduplicated and in order."""
    frames: set = set()
    for job in jobs:
        chunk = job.chunk
        frames.update(chunk.start + i * chunk.inc for i in range(chunk.count))
    return sorted(frames)


def frame_expression(jobs: Sequence[RenderJob]) -> str:
    """Deadline ``Frames=`` value: consecutive runs collapsed, e.g. ``1-10,15,20-25``.

    Explicit runs rather than the chunks' own ``1-19x2`` shorthand, which not
    every scheduler parses the same way.
    """
    frames = all_frames(jobs)
    if not frames:
        return ""

    parts, start, previous = [], frames[0], frames[0]
    for frame in frames[1:]:
        if frame == previous + 1:
            previous = frame
            continue
        parts.append(str(start) if start == previous else f"{start}-{previous}")
        start = previous = frame
    parts.append(str(start) if start == previous else f"{start}-{previous}")
    return ",".join(parts)


def task_command(job: RenderJob, start_token: str) -> list[str]:
    """``job``'s argv with its frame number swapped for the scheduler's token.

    This is what makes a farm submission actually distribute. Emitting one
    job's command verbatim -- which is what this module used to do -- gives
    every task on the farm the same hardcoded ``--frame``, so the whole farm
    re-renders that one chunk and no other frame is ever produced.

    The task renders a single frame (``--frame-count 1``); the scheduler owns
    the splitting, so a per-task increment is meaningless and is dropped.
    """
    argv = list(build_command(job))
    start_flag = "--frame-start" if job.engine == "hython" else "--frame"

    if start_flag in argv:
        argv[argv.index(start_flag) + 1] = start_token
    else:                                   # no frame flag emitted: add one
        argv[1:1] = [start_flag, start_token]

    if "--frame-count" in argv:
        argv[argv.index("--frame-count") + 1] = "1"
    if "--frame-inc" in argv:
        index = argv.index("--frame-inc")
        del argv[index:index + 2]
    return argv


def export_deadline_job(jobs: Sequence[RenderJob], output_dir: str,
                        job_name: str = "Solaris Render") -> tuple[str, str]:
    """Write Thinkbox Deadline job info and plugin info files.

    One Deadline job, one command, frames split by the scheduler. That model
    cannot express "run this after that": dependencies there are between whole
    *jobs*, keyed by job IDs that do not exist until submission.

    So work with dependencies is refused rather than exported. Writing it
    anyway would produce a job that looks right and runs a simulation beside
    the cache feeding it. Use :func:`export_tractor_job`, or submit each task
    as its own Deadline job and wire the dependencies in the submitter.

    Returns (job_info_path, plugin_info_path).
    """
    dependent = [j for j in jobs if j.depends_on]
    if dependent:
        names = ", ".join(sorted({j.task_id or j.label for j in dependent}))
        raise ValueError(
            f"Deadline export cannot express task dependencies ({names} waits "
            f"on other work). Export to Tractor instead, or submit each task "
            f"separately and set the job dependencies in Deadline."
        )

    groups = {j.task_id for j in jobs}
    if len(groups) > 1:
        raise ValueError(
            f"Deadline export writes one job, but these {len(jobs)} chunk(s) "
            f"span {len(groups)} different tasks. Export them one task at a "
            f"time."
        )

    os.makedirs(output_dir, exist_ok=True)
    job_info_path = os.path.join(output_dir, "deadline_job.job")
    plugin_info_path = os.path.join(output_dir, "plugin_info.job")

    first_job = jobs[0] if jobs else RenderJob()
    argv = task_command(first_job, DEADLINE_START_TOKEN)

    with open(job_info_path, "w", encoding="utf-8") as fh:
        fh.write("Plugin=CommandLine\n")
        fh.write(f"Name={job_name}\n")
        fh.write("Comment=Generated by Solaris Render Launcher\n")
        fh.write(f"Frames={frame_expression(jobs)}\n")
        # One frame per task: the command above renders exactly <STARTFRAME>.
        fh.write("ChunkSize=1\n")

    with open(plugin_info_path, "w", encoding="utf-8") as fh:
        executable = argv[0] if argv else "husk"
        fh.write(f"Executable={executable}\n")
        fh.write(f"Arguments={format_command(argv[1:])}\n")

    return job_info_path, plugin_info_path


def _quote_argv(argv) -> str:
    return " ".join(f'"{arg}"' if " " in arg else arg for arg in argv)


def _grouped(jobs: Sequence[RenderJob]):
    """Jobs by ``task_id``, preserving first-seen order."""
    groups: dict = {}
    for job in jobs:
        groups.setdefault(job.task_id, []).append(job)
    return groups


def export_tractor_job(jobs: Sequence[RenderJob], output_path: str,
                       job_name: str = "Solaris Render") -> str:
    """Write a Pixar Tractor .alf script.

    When any job declares a dependency the script becomes a DAG rather than a
    flat list. Emitting dependent work as flat siblings -- which this used to
    do -- lets a farm start a simulation at the same time as the cache feeding
    it, on a different machine, with nothing to serialise them.

    Each task group gets an ``-id`` so a shared dependency is defined once and
    referenced by ``Instance`` rather than run twice. A group that waits on
    something is marked ``-serialsubtasks 1`` with its prerequisites in the
    first subtask and its own chunks in the second, so the chunks cannot start
    until the prerequisites are done.

    Returns output_path.
    """
    out_dir = os.path.dirname(os.path.abspath(output_path))
    if out_dir:
        os.makedirs(out_dir, exist_ok=True)

    lines = [
        '#Alfred-1.0',
        f'Job -title {{{job_name}}} -subservice {{husk}} -children {{',
    ]

    if not any(job.depends_on for job in jobs):
        # Nothing to order: keep the flat shape the Solaris path has always
        # produced rather than wrapping every render in a pointless group.
        for job in jobs:
            lines.append(f'  Task -title {{{job.label}}} -cmds {{')
            lines.append(f'    RemoteCmd {{{_quote_argv(build_command(job))}}}')
            lines.append('  }')
    else:
        for task_id, members in _grouped(jobs).items():
            title = task_id or members[0].label
            deps = []
            for job in members:
                for dep in job.depends_on:
                    if dep not in deps:
                        deps.append(dep)

            chunk_lines = []
            for job in members:
                chunk_lines.append(f'      Task -title {{{job.label}}} -cmds {{')
                chunk_lines.append(
                    f'        RemoteCmd {{{_quote_argv(build_command(job))}}}')
                chunk_lines.append('      }')

            if deps:
                lines.append(f'  Task -title {{{title}}} -id {{{task_id}}} '
                             f'-serialsubtasks 1 -subtasks {{')
                lines.append(f'    Task -title {{{title} waits for}} -subtasks {{')
                for dep in deps:
                    lines.append(f'      Instance {{{dep}}}')
                lines.append('    }')
                lines.append(f'    Task -title {{{title} work}} -subtasks {{')
                lines.extend(chunk_lines)
                lines.append('    }')
                lines.append('  }')
            else:
                lines.append(f'  Task -title {{{title}}} -id {{{task_id}}} '
                             f'-subtasks {{')
                lines.extend(chunk_lines)
                lines.append('  }')

    lines.append('}')

    with open(output_path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")

    return output_path
